#!/usr/bin/env node
// ---------------------------------------------------------------------------
// Packaging script for the Brisa desktop app (Electron).
//
// Resultado: un único artefacto que es a la vez app de escritorio y CLI:
//   - Doble clic  -> ventana nativa (Electron), sin navegador ni puerto visible.
//   - Con args    -> comportamiento CLI (brisa install soh, serve, …) vía
//                    ELECTRON_RUN_AS_NODE sobre una entrada CLI autocontenida
//                    (src/desktop/main.ts hace el despacho).
//
// Pasos:
//   1. Empaqueta la entrada CLI (assets web embebidos) con esbuild en
//      release/gui/cli-entry.cjs  (se copia a resources/ por electron-builder).
//   2. Ejecuta electron-builder: AppImage (Linux) + .zip portable (Windows).
//
// Uso:
//   node scripts/build-desktop.mjs                 # linux + windows
//   node scripts/build-desktop.mjs --only linux    # AppImage
//   node scripts/build-desktop.mjs --only windows  # .zip de Windows
// ---------------------------------------------------------------------------
import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIST = path.join(ROOT, "dist");
const RELEASE = path.join(ROOT, "release");
const GUI_DIR = path.join(RELEASE, "gui");

const args = process.argv.slice(2);
const onlyIdx = args.indexOf("--only");
const ONLY = onlyIdx >= 0 ? args[onlyIdx + 1] : "all";

const step = (msg) => console.log(`\n[build-desktop] ${msg}`);

function run(cmd, cargs, opts = {}) {
  execFileSync(cmd, cargs, { stdio: "inherit", cwd: ROOT, ...opts });
}

const TEXT_DECODER = new TextDecoder("utf-8", { fatal: true });

function isText(buf) {
  if (buf.includes(0)) return false;
  try {
    TEXT_DECODER.decode(buf);
    return true;
  } catch {
    return false;
  }
}

function collectDir(dir, base, out = {}) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) collectDir(abs, rel, out);
    else {
      const buf = fs.readFileSync(abs);
      out[rel] = isText(buf) ? buf.toString("utf8") : `b64:${buf.toString("base64")}`;
    }
  }
  return out;
}

async function bundleCliEntry() {
  step("1/3 Empaquetando entrada CLI (con assets web embebidos)…");
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "brisa-desktop-"));
  try {
    const assets = collectDir(path.join(DIST, "web"), "");
    fs.writeFileSync(
      path.join(tmp, "web-assets.cjs"),
      `// Auto-generated by build-desktop.mjs — do not edit.\nmodule.exports = ${JSON.stringify(assets)};\n`,
    );
    fs.writeFileSync(
      path.join(tmp, "entry.cjs"),
      `globalThis.__WEB_ASSETS__ = require("./web-assets.cjs");\nrequire(${JSON.stringify(path.join(DIST, "cli.js"))});\n`,
    );
    fs.mkdirSync(GUI_DIR, { recursive: true });
    const { build } = await import("esbuild");
    await build({
      entryPoints: [path.join(tmp, "entry.cjs")],
      bundle: true,
      platform: "node",
      format: "cjs",
      target: "node18",
      outfile: path.join(GUI_DIR, "cli-entry.cjs"),
      logLevel: "warning",
    });
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
  console.log(`  → ${path.join(GUI_DIR, "cli-entry.cjs")}`);
}

function wineAvailable() {
  try {
    execFileSync("wine", ["--version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

async function runBuilder() {
  const targets = [];
  const wantLinux = ONLY === "all" || ONLY === "linux";
  const wantWindows = ONLY === "all" || ONLY === "windows";
  if (wantLinux) targets.push("--linux", "AppImage");
  if (wantWindows) {
    // electron-builder necesita wine para editar los recursos del .exe al
    // hacer cross-build desde Linux (icono/versión). En Windows no hace falta.
    if (process.platform === "linux" && !wineAvailable()) {
      console.warn("\n[build-desktop] ⚠  Empaquetar Windows desde Linux requiere wine.");
      console.warn("   Instálalo con: sudo apt install wine   (o ejecuta el build en Windows).\n");
      if (ONLY === "windows") {
        console.error("Abortando: se pidió solo Windows y no hay wine disponible.");
        process.exit(1);
      }
    } else {
      targets.push("--win", "zip");
    }
  }
  step(`2/3 Ejecutando electron-builder (${targets.join(" ")})…`);
  const builder = path.join(ROOT, "node_modules", ".bin", "electron-builder");
  run(builder, targets);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

if (["all", "linux", "windows"].includes(ONLY)) {
  await bundleCliEntry();
  await runBuilder();
  step("3/3 ¡Listo! Artefactos en release/ (AppImage para Linux, .zip para Windows)");
} else {
  console.error("Opción --only inválida. Usa: linux | windows");
  process.exit(1);
}
